name: djangoflow_websocket
description: Easily manage connecting to a WebSocket server, subscribing to messages, handling reconnections etc all at once with djangoflow_websocket
version: 0.4.0
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_websocket

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^9.0.0
  djangoflow_bloc_extensions: ^0.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.0
