name: djangoflow_chat
description: The djangoflow_chat package provides a set of classes and methods for building real-time chat applications in Flutter using [django-df-chat](https://github.com/djangoflow/django-df-chat) and djangoflow_openapi
version: 0.3.0
homepage: https://github.com/djangoflow/flutter-djangoflow/

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^9.0.0
  collection: ^1.18.0
  dio: ^5.4.2+1
  djangoflow_bloc_extensions: ^0.2.0
  djangoflow_openapi: ^0.1.22
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.7.1

flutter:
