name: djangoflow
repository: https://github.com/djangoflow/flutter-djangoflow

packages:
  - packages/*djangoflow*
  - packages/**/*djangoflow*

command:
  version:
    linkToCommits: true
    workspaceChangelog: true
    branch: main
    updateGitTagRefs: true
    
  bootstrap:
    runPubGetInParallel: false
    hooks:
      post: melos run generate:dart

scripts:
  flutter:upgrade:
    description: |
      Upgrades all packages (Flutter).
    run: flutter pub upgrade
    exec:
      concurrency: 1
    packageFilters:
      scope: "*djangoflow*"
      ignore: 
        - "*example*"
        - "*djangoflow_openapi*"
      flutter: true
  
  flutter:upgrade:major:
    description: |
      Upgrades all packages with major versions (Flutter).
    run: flutter pub upgrade --major-versions
    exec:
      concurrency: 1
    packageFilters:
      scope: "*djangoflow*"
      ignore: 
        - "*example*"
        - "*djangoflow_openapi*"
      flutter: true
      
      
  format:
    run: dart format .
    description: Formats the code of all packages (Dart).
    exec: 
      concurrency: 1
      failFast: true
    packageFilters:
      ignore: 
        - "*djangoflow_openapi*"

  generate:dart:
    run: dart run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1
      failFast: true
    description: Generate build_runner files
    packageFilters:
      dependsOn: 'build_runner'
      flutter: true
      scope: "*djangoflow*"
      ignore:
        - "*/example/*"