name: djangoflow_remote_config
description: Djangoflow Remote Config is a library that helps to handle remote config in your flutter application.
version: 0.2.0
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_remote_config

environment:
  sdk: ">=3.1.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.3.3
  djangoflow_bloc_extensions: ^0.2.0
  djangoflow_openapi: ^0.1.22
  djangoflow_openapi_extensions: ^0.0.3+4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  hydrated_bloc: ^10.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
