name: djangoflow_error_reporter
description: Djangoflow Error Reporter is a library that provides an easy and flexible way to handle errors in your flutter application.
version: 0.3.0
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_error_reporters/djangoflow_error_reporter

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
