name: djangoflow_odoo_auth
description: "Odoo Authentication package for Flutter"
version: 0.1.0+3
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_odoo/authentication/djangoflow_odoo_auth

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.5
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  http: ^1.2.2
  hydrated_bloc: ^10.0.0
  odoo_rpc:
    git:
      url: https://github.com/djangoflow/odoo-rpc-dart.git
      ref: master
  xml_rpc: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
