name: djangoflow_mixpanel_analytics
description: A library provides an easy and organized way to implement Mixpanel Analytics for your Flutter apps.
version: 0.5.0+1
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_analytics/djangoflow_mixpanel_analytics

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  # Need to update
  analytics: ^1.0.2
  djangoflow_analytics: ^0.1.0+1
  flutter:
    sdk: flutter
  # need to update
  mixpanel_flutter: ^2.3.3
  mockito: ^5.4.4

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
