name: djangoflow_firebase_messaging
description: A package to integrate Firebase Cloud Messaging into djangoflow app
version: 1.0.0
homepage: https://github.com/djangoflow/flutter-djangoflow/

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^14.2.0
  app_settings: ^4.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1