name: djangoflow_sentry_reporter
description: A library that allows you to report errors to `Sentry` using the `djangoflow_error_reporter` pacakge.
version: 0.4.0
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_error_reporters/djangoflow_sentry_reporter

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  djangoflow_error_reporter: ^0.3.0
  flutter:
    sdk: flutter
  sentry_flutter: ^8.11.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
