name: djangoflow_odoo_oauth
description: "Odoo OAuth Authentication package for Flutter"
version: 0.1.0+1
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_odoo/authentication/djangoflow_odoo_oauth

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  crypto: ^3.0.5
  djangoflow_oauth: ^0.0.1+1
  flutter:
    sdk: flutter
  flutter_web_auth_2: ^4.0.2
  html: ^0.15.5
  http: ^1.2.2
  webview_cookie_manager: ^2.0.6
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
