name: djangoflow_fcm
description: A Djangoflow Flutter project to handle notifications using firebase_messaging
version: 0.2.0+1
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_push_notification/djangoflow_fcm

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc_test: ^10.0.0
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  firebase_messaging_platform_interface: ^4.5.48
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  mockito: ^5.4.3

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.0
