name: example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  djangoflow_sentry_reporter:
    path: ../
  djangoflow_error_reporter:
    path: ../../djangoflow_error_reporter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  djangoflow_error_reporter:
    path: ../../djangoflow_error_reporter

flutter:
  uses-material-design: true
