name: djangoflow_app
description: A simple, opinionated, and minimal Flutter application structure for quick start and easy maintenance.
version: 3.1.0
homepage: https://github.com/djangoflow/flutter-djangoflow/

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  package_info_plus: ^3.0.2
  path_provider: ^2.0.11
  hydrated_bloc: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  json_serializable: ^6.5.4
